import type { Metadata } from 'next'
import { Jura, Koulen } from 'next/font/google'

const jura = Jura({ subsets: ['latin'] })
const koulen = Koulen({
  subsets: ['khmer'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function CoursesLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ background: "#DBEFB3" }}>
        <div className='max-w-[1400px] w-full mx-auto'>
          {children}
        </div>
      </body>
    </html>
  )
}
